define(function(require){
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/scrollView/scrollView');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/bootstrap/row/row');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/windowDialog/windowDialog');
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/output/output');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/button/buttonGroup');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/TheSaleEnterprise/CustomerManagement/dialog/orderQuery'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='';
	this.__cid='cr6faEb';
	this._flag_='9df2c307cef2b6a73b24429524eba531';
	this._wCfg_={};
	this._appCfg_={};
	this.callParent(contextUrl);
 require('css!$UI/TheSaleEnterprise/css/style').load();
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"cusType":{"define":"cusType","name":"cusType","relation":"cusType","type":"String"},"dhje":{"define":"dhje","name":"dhje","relation":"dhje","type":"String"},"djsl":{"define":"djsl","name":"djsl","relation":"djsl","type":"String"},"fhzt":{"define":"fhzt","name":"fhzt","relation":"fhzt","type":"String"},"id":{"define":"id","name":"id","relation":"id","type":"String"},"khmc":{"define":"khmc","name":"khmc","relation":"khmc","type":"String"},"shzt":{"define":"shzt","name":"shzt","relation":"shzt","type":"String"},"sn":{"define":"sn","name":"sn","relation":"sn","type":"String"},"sqr":{"define":"sqr","name":"sqr","relation":"sqr","type":"String"},"sqrmc":{"define":"sqrmc","name":"sqrmc","relation":"sqrmc","type":"String"},"sqrq":{"define":"sqrq","name":"sqrq","relation":"sqrq","type":"String"},"status":{"define":"status","name":"status","relation":"status","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","isMain":false,"limit":20,"xid":"orderData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"address":{"define":"address","name":"address","relation":"address","type":"String"},"code":{"define":"code","name":"code","relation":"code","type":"String"},"col8":{"define":"col8","name":"col8","relation":"col8","type":"String"},"col9":{"define":"col9","name":"col9","relation":"col9","type":"String"},"daogou":{"define":"daogou","name":"daogou","relation":"daogou","type":"String"},"id":{"define":"id","name":"id","relation":"id","type":"String"},"name":{"define":"name","name":"name","relation":"name","type":"String"},"state":{"define":"state","name":"state","relation":"state","type":"String"},"time":{"define":"time","name":"time","relation":"time","type":"String"},"zhongdian":{"define":"zhongdian","name":"zhongdian","relation":"zhongdian","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","isMain":false,"limit":20,"xid":"InData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"cusType":{"define":"cusType","name":"cusType","relation":"cusType","type":"String"},"dhje":{"define":"dhje","name":"dhje","relation":"dhje","type":"String"},"djsl":{"define":"djsl","name":"djsl","relation":"djsl","type":"String"},"fhzt":{"define":"fhzt","name":"fhzt","relation":"fhzt","type":"String"},"id":{"define":"id","name":"id","relation":"id","type":"String"},"khmc":{"define":"khmc","name":"khmc","relation":"khmc","type":"String"},"shzt":{"define":"shzt","name":"shzt","relation":"shzt","type":"String"},"sn":{"define":"sn","name":"sn","relation":"sn","type":"String"},"sqr":{"define":"sqr","name":"sqr","relation":"sqr","type":"String"},"sqrmc":{"define":"sqrmc","name":"sqrmc","relation":"sqrmc","type":"String"},"sqrq":{"define":"sqrq","name":"sqrq","relation":"sqrq","type":"String"},"status":{"define":"status","name":"status","relation":"status","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","isMain":false,"limit":20,"xid":"orderData1"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"cusType":{"define":"cusType","name":"cusType","relation":"cusType","type":"String"},"dhje":{"define":"dhje","name":"dhje","relation":"dhje","type":"String"},"djsl":{"define":"djsl","name":"djsl","relation":"djsl","type":"String"},"fhzt":{"define":"fhzt","name":"fhzt","relation":"fhzt","type":"String"},"id":{"define":"id","name":"id","relation":"id","type":"String"},"khmc":{"define":"khmc","name":"khmc","relation":"khmc","type":"String"},"shzt":{"define":"shzt","name":"shzt","relation":"shzt","type":"String"},"sn":{"define":"sn","name":"sn","relation":"sn","type":"String"},"sqr":{"define":"sqr","name":"sqr","relation":"sqr","type":"String"},"sqrmc":{"define":"sqrmc","name":"sqrmc","relation":"sqrmc","type":"String"},"sqrq":{"define":"sqrq","name":"sqrq","relation":"sqrq","type":"String"},"status":{"define":"status","name":"status","relation":"status","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","isMain":false,"limit":20,"xid":"orderData2"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"cusType":{"define":"cusType","name":"cusType","relation":"cusType","type":"String"},"dhje":{"define":"dhje","name":"dhje","relation":"dhje","type":"String"},"djsl":{"define":"djsl","name":"djsl","relation":"djsl","type":"String"},"fhzt":{"define":"fhzt","name":"fhzt","relation":"fhzt","type":"String"},"id":{"define":"id","name":"id","relation":"id","type":"String"},"khmc":{"define":"khmc","name":"khmc","relation":"khmc","type":"String"},"shzt":{"define":"shzt","name":"shzt","relation":"shzt","type":"String"},"sn":{"define":"sn","name":"sn","relation":"sn","type":"String"},"sqr":{"define":"sqr","name":"sqr","relation":"sqr","type":"String"},"sqrmc":{"define":"sqrmc","name":"sqrmc","relation":"sqrmc","type":"String"},"sqrq":{"define":"sqrq","name":"sqrq","relation":"sqrq","type":"String"},"status":{"define":"status","name":"status","relation":"status","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","isMain":false,"limit":20,"xid":"orderData3"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"cusType":{"define":"cusType","name":"cusType","relation":"cusType","type":"String"},"dhje":{"define":"dhje","name":"dhje","relation":"dhje","type":"String"},"djsl":{"define":"djsl","name":"djsl","relation":"djsl","type":"String"},"fhzt":{"define":"fhzt","name":"fhzt","relation":"fhzt","type":"String"},"id":{"define":"id","name":"id","relation":"id","type":"String"},"khmc":{"define":"khmc","name":"khmc","relation":"khmc","type":"String"},"shzt":{"define":"shzt","name":"shzt","relation":"shzt","type":"String"},"sn":{"define":"sn","name":"sn","relation":"sn","type":"String"},"sqr":{"define":"sqr","name":"sqr","relation":"sqr","type":"String"},"sqrmc":{"define":"sqrmc","name":"sqrmc","relation":"sqrmc","type":"String"},"sqrq":{"define":"sqrq","name":"sqrq","relation":"sqrq","type":"String"},"status":{"define":"status","name":"status","relation":"status","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","isMain":false,"limit":20,"xid":"orderData4"});
}}); 
return __result;});